#define color_reset   "\x1B[0m"
#define bright        "\x1b[1m"

#define fore_black    "\x1B[30m"
#define fore_red      "\x1B[31m"
#define fore_green    "\x1B[32m"
#define fore_yellow   "\x1B[33m"
#define fore_blue     "\x1B[34m"
#define fore_magenta  "\x1B[35m"
#define fore_cyan     "\x1B[36m"
#define fore_white    "\x1B[37m"

#define back_black    "\x1B[40m"
#define back_red      "\x1B[41m"
#define back_green    "\x1B[42m"
#define back_yellow   "\x1B[44m"
#define back_blue     "\x1B[44m"
#define back_magenta  "\x1B[45m"
#define back_cyan     "\x1B[46m"
#define back_white    "\x1B[47m"
